In [72]:
import pandas as pd
import numpy as np
import time
import json
import requests
from datetime import date
from matplotlib import pyplot as plt
import datetime

In [73]:
county_level_feat = pd.read_csv('county_features_final.csv')

In [81]:
chosen_county_feat = np.unique(county_level_feat.title.values)
print(np.unique(county_level_feat['frequency']))
print(len(chosen_county_feat))
print(chosen_county_feat)

['Annual' 'Monthly' 'Quarterly']
73
['90% Confidence Interval Lower Bound of Estimate of Median Household Income'
 '90% Confidence Interval Lower Bound of Estimate of People Age 0-17 in Poverty'
 '90% Confidence Interval Lower Bound of Estimate of People of All Ages in Poverty'
 '90% Confidence Interval Lower Bound of Estimate of Percent of People Age 0-17 in Poverty'
 '90% Confidence Interval Lower Bound of Estimate of Percent of People of All Ages in Poverty'
 '90% Confidence Interval Lower Bound of Estimate of Percent of Related Children Age 5-17 in Families in Poverty'
 '90% Confidence Interval Lower Bound of Estimate of Related Children Age 5-17 in Families in Poverty'
 '90% Confidence Interval Upper Bound of Estimate of Median Household Income'
 '90% Confidence Interval Upper Bound of Estimate of People Age 0-17 in Poverty'
 '90% Confidence Interval Upper Bound of Estimate of People of All Ages in Poverty'
 '90% Confidence Interval Upper Bound of Estimate of Percent of People Age 0-17 in Poverty'
 '90% Confidence Interval Upper Bound of Estimate of Percent of People of All Ages in Poverty'
 '90% Confidence Interval Upper Bound of Estimate of Percent of Related Children Age 5-17 in Families in Poverty'
 '90% Confidence Interval Upper Bound of Estimate of Related Children Age 5-17 in Families in Poverty'
 'All-Transactions House Price Index'
 "Bachelor's Degree or Higher (5-year estimate)" 'Burdened Households'
 'Civilian Labor Force'
 'Combined Violent and Property Crime Incidents Known to Law Enforcement'
 'Disconnected Youth (5-year estimate)' 'Employed Persons'
 'Equifax Subprime Credit Population'
 'Estimate of Median Household Income'
 'Estimate of People Age 0-17 in Poverty'
 'Estimate of People of All Ages in Poverty'
 'Estimate of Related Children Age 5-17 in Families in Poverty'
 'Estimate, Median Age by Sex, Total Population (5-year estimate)'
 'Estimated Percent of People Age 0-17 in Poverty'
 'Estimated Percent of People of All Ages in Poverty'
 'Estimated Percent of Related Children Age 5-17 in Families in Poverty'
 'Gross Domestic Product: All Industries'
 'Gross Domestic Product: Government and Government Enterprises'
 'High School Graduate or Higher (5-year estimate)'
 'Homeownership Rate (5-year estimate)' 'Income Inequality'
 'Mean Commuting Time'
 'Net County-to-County Migration Flow (5-year estimate)'
 'New Private Housing Structures Authorized by Building Permits'
 'Number of Private Establishments'
 "People 25 Years and Over Who Have Completed an Associate's Degree or Higher (5-year estimate)"
 'Per Capita Personal Income' 'Personal Income'
 'Population Estimate, Total (5-year estimate)'
 'Population Estimate, Total, Hispanic or Latino (5-year estimate)'
 'Population Estimate, Total, Hispanic or Latino, American Indian and Alaska Native Alone (5-year estimate)'
 'Population Estimate, Total, Hispanic or Latino, Asian Alone (5-year estimate)'
 'Population Estimate, Total, Hispanic or Latino, Black or African American Alone (5-year estimate)'
 'Population Estimate, Total, Hispanic or Latino, Native Hawaiian and Other Pacific Islander Alone (5-year estimate)'
 'Population Estimate, Total, Hispanic or Latino, Some Other Race Alone (5-year estimate)'
 'Population Estimate, Total, Hispanic or Latino, Two or More Races (5-year estimate)'
 'Population Estimate, Total, Hispanic or Latino, Two or More Races, Two Races Excluding Some Other Race, and Three or More Races (5-year estimate)'
 'Population Estimate, Total, Hispanic or Latino, Two or More Races, Two Races Including Some Other Race (5-year estimate)'
 'Population Estimate, Total, Hispanic or Latino, White Alone (5-year estimate)'
 'Population Estimate, Total, Not Hispanic or Latino (5-year estimate)'
 'Population Estimate, Total, Not Hispanic or Latino, American Indian and Alaska Native Alone (5-year estimate)'
 'Population Estimate, Total, Not Hispanic or Latino, Asian Alone (5-year estimate)'
 'Population Estimate, Total, Not Hispanic or Latino, Black or African American Alone (5-year estimate)'
 'Population Estimate, Total, Not Hispanic or Latino, Native Hawaiian and Other Pacific Islander Alone (5-year estimate)'
 'Population Estimate, Total, Not Hispanic or Latino, Some Other Race Alone (5-year estimate)'
 'Population Estimate, Total, Not Hispanic or Latino, Two or More Races (5-year estimate)'
 'Population Estimate, Total, Not Hispanic or Latino, Two or More Races, Two Races Excluding Some Other Race, and Three or More Races (5-year estimate)'
 'Population Estimate, Total, Not Hispanic or Latino, Two or More Races, Two Races Including Some Other Race (5-year estimate)'
 'Population Estimate, Total, Not Hispanic or Latino, White Alone (5-year estimate)'
 'Poverty Universe, Age 0-17' 'Poverty Universe, Age 5-17 related'
 'Poverty Universe, All Ages'
 'Real Gross Domestic Product: All Industries'
 'Real Gross Domestic Product: Government and Government Enterprises'
 'Resident Population' 'SNAP Benefits Recipients'
 'Single-parent Households with Children as a Percentage of Households with Children'
 'Unemployed Persons' 'Unemployment Rate']

In [78]:
county_level_feat.head()

,Unnamed: 0,frequency,id,observation_end,observation_start,seasonal_adjustment,title,units,county_id,num_months
109050,109050,Annual,2020RATIO047005,2018-01-01,2010-01-01,Not Seasonally Adjusted,Income Inequality,Ratio,204,96
109051,109051,Annual,ATNHPIUS47005A,2018-01-01,1996-01-01,Not Seasonally Adjusted,All-Transactions House Price Index,Index 2000=100,204,264
109052,109052,Annual,B01002001E047005,2018-01-01,2009-01-01,Not Seasonally Adjusted,"Estimate, Median Age by Sex, Total Population ...",Years of Age,204,108
109053,109053,Annual,B03002001E047005,2018-01-01,2009-01-01,Not Seasonally Adjusted,"Population Estimate, Total (5-year estimate)",Persons,204,108
109054,109054,Annual,B03002002E047005,2018-01-01,2009-01-01,Not Seasonally Adjusted,"Population Estimate, Total, Not Hispanic or La...",Persons,204,108

In [76]:
county_level_feat = county_level_feat.sort_values(["county_id", "id"])

In [106]:
counties_list = county_level_feat['county_id'].values
time_freq = county_level_feat['frequency'].values
df_series_table = pd.DataFrame()
series_table_cols = ['id', 'title', 'observation_start', 'observation_end', 'frequency', 'units', 'seasonal_adjustment']
start = 0
end = 1
count = 0
for county_id, freq in zip(counties_list[start:end], time_freq[start:end]):
    time.sleep(.5)
    params = {
        'category_id': county_id,
        'api_key': 'e76fcf746d3ca3cc025c0803dd212fc8',
        'file_type': 'json'
    }
    r = requests.get(url = 'https://api.stlouisfed.org/fred/category/series', params=params)
    res = r.json()
    
    # Get the observations for a series
    seriess = res['seriess']
    for series in range(len(seriess)):
        current_series = seriess[series]
        series_id = current_series['id']
        
        params = {
            'series_id': series_id,
            'api_key': 'e76fcf746d3ca3cc025c0803dd212fc8',
            'file_type': 'json'
        }
        r = requests.get(url = 'https://api.stlouisfed.org/fred/series/observations', params=params)
        res1 = r.json()

        res1["observations"] = [i for i in res1["observations"] if not (int(i["date"][0:4]) < 2010 or int(i["date"][0:4]) > 2017)]
        
        for val in res1["observations"]:
            del val["realtime_start"]
            del val["realtime_end"]
            print(val)
            
        #todo: repeat the date thingies, pull the data, put in table
        
#         if (freq == "Annual"):
#             print('im here tho')
#             for val in res1["observations"]:
#                 print(val)
#         elif (freq == "Quarterly"):
#             for val in res1["observations"]:
#                 print(val)
#         else: #monthly
#             for val in res1["observations"]:
#                 print(val)
        
#     print(seriess[0])
#     for item in seriess:
#         print(item["id"])
#         count = count + 1
#     print(count)
#     series_in_county = pd.DataFrame()
#     for series in seriess:
#         temp = { your_key: series[your_key] for your_key in series_table_cols }
#         print(your_key)
#         temp['title'] = get_series_name(county_name, temp['title'])
#         series_in_county = series_in_county.append(temp, ignore_index=True)
#     series_in_county['county_id'] = county_id
#     df_series_table = df_series_table.append(series_in_county)

# print(df_series_table.shape)

{'date': '2010-01-01', 'value': '11.887555348403636'}
{'date': '2011-01-01', 'value': '10.446813115463694'}
{'date': '2012-01-01', 'value': '10.549546560495466'}
{'date': '2013-01-01', 'value': '12.371719401520727'}
{'date': '2014-01-01', 'value': '12.129924462521789'}
{'date': '2015-01-01', 'value': '13.558107602047185'}
{'date': '2016-01-01', 'value': '15.185372824110159'}
{'date': '2017-01-01', 'value': '16.567867786507723'}
{'date': '2010-01-01', 'value': '120.81'}
{'date': '2011-01-01', 'value': '114.13'}
{'date': '2012-01-01', 'value': '115.23'}
{'date': '2013-01-01', 'value': '114.13'}
{'date': '2014-01-01', 'value': '127.74'}
{'date': '2015-01-01', 'value': '120.63'}
{'date': '2016-01-01', 'value': '140.03'}
{'date': '2017-01-01', 'value': '124.77'}
{'date': '2010-01-01', 'value': '45.1'}
{'date': '2011-01-01', 'value': '45.8'}
{'date': '2012-01-01', 'value': '46.0'}
{'date': '2013-01-01', 'value': '46.1'}
{'date': '2014-01-01', 'value': '45.9'}
{'date': '2015-01-01', 'value': '46.1'}
{'date': '2016-01-01', 'value': '46.6'}
{'date': '2017-01-01', 'value': '46.5'}
{'date': '2010-01-01', 'value': '16456'}
{'date': '2011-01-01', 'value': '16451'}
{'date': '2012-01-01', 'value': '16420'}
{'date': '2013-01-01', 'value': '16398'}
{'date': '2014-01-01', 'value': '16345'}
{'date': '2015-01-01', 'value': '16261'}
{'date': '2016-01-01', 'value': '16173'}
{'date': '2017-01-01', 'value': '16154'}
{'date': '2010-01-01', 'value': '16202'}
{'date': '2011-01-01', 'value': '16175'}
{'date': '2012-01-01', 'value': '16114'}
{'date': '2013-01-01', 'value': '16082'}
{'date': '2014-01-01', 'value': '16015'}
{'date': '2015-01-01', 'value': '15922'}
{'date': '2016-01-01', 'value': '15818'}
{'date': '2017-01-01', 'value': '15798'}
{'date': '2010-01-01', 'value': '15591.0'}
{'date': '2011-01-01', 'value': '15550.0'}
{'date': '2012-01-01', 'value': '15460.0'}
{'date': '2013-01-01', 'value': '15395.0'}
{'date': '2014-01-01', 'value': '15294.0'}
{'date': '2015-01-01', 'value': '15175.0'}
{'date': '2016-01-01', 'value': '15066'}
{'date': '2017-01-01', 'value': '15048'}
{'date': '2010-01-01', 'value': '378.0'}
{'date': '2011-01-01', 'value': '422.0'}
{'date': '2012-01-01', 'value': '413.0'}
{'date': '2013-01-01', 'value': '412.0'}
{'date': '2014-01-01', 'value': '581.0'}
{'date': '2015-01-01', 'value': '563.0'}
{'date': '2016-01-01', 'value': '466'}
{'date': '2017-01-01', 'value': '556'}
{'date': '2010-01-01', 'value': '35.0'}
{'date': '2011-01-01', 'value': '31.0'}
{'date': '2012-01-01', 'value': '46.0'}
{'date': '2013-01-01', 'value': '52.0'}
{'date': '2014-01-01', 'value': '28.0'}
{'date': '2015-01-01', 'value': '31.0'}
{'date': '2016-01-01', 'value': '53'}
{'date': '2017-01-01', 'value': '55'}
{'date': '2010-01-01', 'value': '11.0'}
{'date': '2011-01-01', 'value': '5.0'}
{'date': '2012-01-01', 'value': '53.0'}
{'date': '2013-01-01', 'value': '91.0'}
{'date': '2014-01-01', 'value': '51.0'}
{'date': '2015-01-01', 'value': '82.0'}
{'date': '2016-01-01', 'value': '102'}
{'date': '2017-01-01', 'value': '6'}
{'date': '2010-01-01', 'value': '0'}
{'date': '2011-01-01', 'value': '0'}
{'date': '2012-01-01', 'value': '0'}
{'date': '2013-01-01', 'value': '0'}
{'date': '2014-01-01', 'value': '0'}
{'date': '2015-01-01', 'value': '0'}
{'date': '2016-01-01', 'value': '0'}
{'date': '2017-01-01', 'value': '0'}
{'date': '2010-01-01', 'value': '0'}
{'date': '2011-01-01', 'value': '0'}
{'date': '2012-01-01', 'value': '0'}
{'date': '2013-01-01', 'value': '0'}
{'date': '2014-01-01', 'value': '0'}
{'date': '2015-01-01', 'value': '0'}
{'date': '2016-01-01', 'value': '0'}
{'date': '2017-01-01', 'value': '0'}
{'date': '2010-01-01', 'value': '187'}
{'date': '2011-01-01', 'value': '167'}
{'date': '2012-01-01', 'value': '142'}
{'date': '2013-01-01', 'value': '132'}
{'date': '2014-01-01', 'value': '61'}
{'date': '2015-01-01', 'value': '71'}
{'date': '2016-01-01', 'value': '131'}
{'date': '2017-01-01', 'value': '133'}
{'date': '2010-01-01', 'value': '0'}
{'date': '2011-01-01', 'value': '0'}
{'date': '2012-01-01', 'value': '0'}
{'date': '2013-01-01', 'value': '0'}
{'date': '2014-01-01', 'value': '0'}
{'date': '2015-01-01', 'value': '0'}
{'date': '2016-01-01', 'value': '9'}
{'date': '2017-01-01', 'value': '9'}
{'date': '2010-01-01', 'value': '187'}
{'date': '2011-01-01', 'value': '167'}
{'date': '2012-01-01', 'value': '142'}
{'date': '2013-01-01', 'value': '132'}
{'date': '2014-01-01', 'value': '61'}
{'date': '2015-01-01', 'value': '71'}
{'date': '2016-01-01', 'value': '122'}
{'date': '2017-01-01', 'value': '124'}
{'date': '2010-01-01', 'value': '254.0'}
{'date': '2011-01-01', 'value': '276.0'}
{'date': '2012-01-01', 'value': '306.0'}
{'date': '2013-01-01', 'value': '316.0'}
{'date': '2014-01-01', 'value': '330.0'}
{'date': '2015-01-01', 'value': '339.0'}
{'date': '2016-01-01', 'value': '355'}
{'date': '2017-01-01', 'value': '356'}
{'date': '2010-01-01', 'value': '222'}
{'date': '2011-01-01', 'value': '240'}
{'date': '2012-01-01', 'value': '295'}
{'date': '2013-01-01', 'value': '300'}
{'date': '2014-01-01', 'value': '309'}
{'date': '2015-01-01', 'value': '308'}
{'date': '2016-01-01', 'value': '335'}
{'date': '2017-01-01', 'value': '320'}
{'date': '2010-01-01', 'value': '0'}
{'date': '2011-01-01', 'value': '0'}
{'date': '2012-01-01', 'value': '0'}
{'date': '2013-01-01', 'value': '0'}
{'date': '2014-01-01', 'value': '0'}
{'date': '2015-01-01', 'value': '0'}
{'date': '2016-01-01', 'value': '0'}
{'date': '2017-01-01', 'value': '0'}
{'date': '2010-01-01', 'value': '0'}
{'date': '2011-01-01', 'value': '0'}
{'date': '2012-01-01', 'value': '0'}
{'date': '2013-01-01', 'value': '0'}
{'date': '2014-01-01', 'value': '0'}
{'date': '2015-01-01', 'value': '0'}
{'date': '2016-01-01', 'value': '0'}
{'date': '2017-01-01', 'value': '0'}
{'date': '2010-01-01', 'value': '0'}
{'date': '2011-01-01', 'value': '0'}
{'date': '2012-01-01', 'value': '0'}
{'date': '2013-01-01', 'value': '0'}
{'date': '2014-01-01', 'value': '0'}
{'date': '2015-01-01', 'value': '3'}
{'date': '2016-01-01', 'value': '7'}
{'date': '2017-01-01', 'value': '15'}
{'date': '2010-01-01', 'value': '0'}
{'date': '2011-01-01', 'value': '0'}
{'date': '2012-01-01', 'value': '0'}
{'date': '2013-01-01', 'value': '0'}
{'date': '2014-01-01', 'value': '0'}
{'date': '2015-01-01', 'value': '0'}
{'date': '2016-01-01', 'value': '0'}
{'date': '2017-01-01', 'value': '0'}
{'date': '2010-01-01', 'value': '32'}
{'date': '2011-01-01', 'value': '28'}
{'date': '2012-01-01', 'value': '9'}
{'date': '2013-01-01', 'value': '11'}
{'date': '2014-01-01', 'value': '17'}
{'date': '2015-01-01', 'value': '17'}
{'date': '2016-01-01', 'value': '10'}
{'date': '2017-01-01', 'value': '13'}
{'date': '2010-01-01', 'value': '0'}
{'date': '2011-01-01', 'value': '8'}
{'date': '2012-01-01', 'value': '2'}
{'date': '2013-01-01', 'value': '5'}
{'date': '2014-01-01', 'value': '4'}
{'date': '2015-01-01', 'value': '11'}
{'date': '2016-01-01', 'value': '3'}
{'date': '2017-01-01', 'value': '8'}
{'date': '2010-01-01', 'value': '0'}
{'date': '2011-01-01', 'value': '8'}
{'date': '2012-01-01', 'value': '2'}
{'date': '2013-01-01', 'value': '5'}
{'date': '2014-01-01', 'value': '4'}
{'date': '2015-01-01', 'value': '7'}
{'date': '2016-01-01', 'value': '0'}
{'date': '2017-01-01', 'value': '0'}
{'date': '2010-01-01', 'value': '0'}
{'date': '2011-01-01', 'value': '0'}
{'date': '2012-01-01', 'value': '0'}
{'date': '2013-01-01', 'value': '0'}
{'date': '2014-01-01', 'value': '0'}
{'date': '2015-01-01', 'value': '4'}
{'date': '2016-01-01', 'value': '3'}
{'date': '2017-01-01', 'value': '8'}
{'date': '2010-01-01', 'value': '23.482632541133455'}
{'date': '2011-01-01', 'value': '24.09593468276918'}
{'date': '2012-01-01', 'value': '24.086225596529285'}
{'date': '2013-01-01', 'value': '23.585162343551605'}
{'date': '2014-01-01', 'value': '23.960153792380286'}
{'date': '2015-01-01', 'value': '24.49349945828819'}
{'date': '2016-01-01', 'value': '23.627659574468087'}
{'date': '2017-01-01', 'value': '24.39535309184047'}
{'date': '2010-01-01', 'value': '14.987080103359174'}
{'date': '2011-01-01', 'value': '11.940298507462686'}
{'date': '2012-01-01', 'value': '15.894868585732166'}
{'date': '2013-01-01', 'value': '5.443037974683544'}
{'date': '2014-01-01', 'value': '3.6719706242350063'}
{'date': '2015-01-01', 'value': '4.25531914893617'}
{'date': '2016-01-01', 'value': '2.631578947368421'}
{'date': '2017-01-01', 'value': '8.19277108433735'}

{'date': '2010-01-01', 'value': '0'}
{'date': '2011-01-01', 'value': '50'}
{'date': '2012-01-01', 'value': '2'}
{'date': '2013-01-01', 'value': '5'}
{'date': '2014-01-01', 'value': '0'}
{'date': '2015-01-01', 'value': '3'}
{'date': '2016-01-01', 'value': '10.0'}
{'date': '2017-01-01', 'value': '23.0'}
{'date': '2010-01-01', 'value': '3794'}
{'date': '2011-01-01', 'value': '3747'}
{'date': '2012-01-01', 'value': '3769'}
{'date': '2013-01-01', 'value': '3921'}
{'date': '2014-01-01', 'value': '3601'}
{'date': '2015-01-01', 'value': '3200'}
{'date': '2016-01-01', 'value': '3121'}
{'date': '2017-01-01', 'value': '2904'}
{'date': '2010-01-01', 'value': '896.9'}
{'date': '2011-01-01', 'value': '816.9'}
{'date': '2012-01-01', 'value': '926.8'}
{'date': '2013-01-01', 'value': '859.7'}
{'date': '2014-01-01', 'value': '997.8'}
{'date': '2015-01-01', 'value': '885.1'}
{'date': '2016-01-01', 'value': '962.9'}
{'date': '2017-01-01', 'value': '962.9'}
{'date': '2010-01-01', 'value': '641.6'}
{'date': '2011-01-01', 'value': '526.0'}
{'date': '2012-01-01', 'value': '634.5'}
{'date': '2013-01-01', 'value': '603.7'}
{'date': '2014-01-01', 'value': '643.5'}
{'date': '2015-01-01', 'value': '572.2'}
{'date': '2016-01-01', 'value': '609.8'}
{'date': '2017-01-01', 'value': '637.9'}
{'date': '2010-01-01', 'value': '91.1499998569489'}
{'date': '2011-01-01', 'value': '94.4099999992177'}
{'date': '2012-01-01', 'value': '97.6959999995306'}
{'date': '2013-01-01', 'value': '78.0179999992251'}
{'date': '2014-01-01', 'value': '70.5969999991357'}
{'date': '2015-01-01', 'value': '75.2279999991879'}
{'date': '2010-01-01', 'value': '24.137931034482758'}
{'date': '2011-01-01', 'value': '25.540275049115913'}
{'date': '2012-01-01', 'value': '27.129337539432175'}
{'date': '2013-01-01', 'value': '28.197989172467132'}
{'date': '2014-01-01', 'value': '28.227435140593442'}
{'date': '2015-01-01', 'value': '29.75011786892975'}
{'date': '2016-01-01', 'value': '28.134270101483217'}
{'date': '2017-01-01', 'value': '29.458982180125222'}
{'date': '2010-01-01', 'value': '269'}
{'date': '2010-04-01', 'value': '269'}
{'date': '2010-07-01', 'value': '270'}
{'date': '2010-10-01', 'value': '270'}
{'date': '2011-01-01', 'value': '265'}
{'date': '2011-04-01', 'value': '264'}
{'date': '2011-07-01', 'value': '261'}
{'date': '2011-10-01', 'value': '263'}
{'date': '2012-01-01', 'value': '261'}
{'date': '2012-04-01', 'value': '261'}
{'date': '2012-07-01', 'value': '260'}
{'date': '2012-10-01', 'value': '259'}
{'date': '2013-01-01', 'value': '259'}
{'date': '2013-04-01', 'value': '254'}
{'date': '2013-07-01', 'value': '255'}
{'date': '2013-10-01', 'value': '260'}
{'date': '2014-01-01', 'value': '257'}
{'date': '2014-04-01', 'value': '262'}
{'date': '2014-07-01', 'value': '259'}
{'date': '2014-10-01', 'value': '265'}
{'date': '2015-01-01', 'value': '258'}
{'date': '2015-04-01', 'value': '265'}
{'date': '2015-07-01', 'value': '263'}
{'date': '2015-10-01', 'value': '261'}
{'date': '2016-01-01', 'value': '266'}
{'date': '2016-04-01', 'value': '264'}
{'date': '2016-07-01', 'value': '265'}
{'date': '2016-10-01', 'value': '268'}
{'date': '2017-01-01', 'value': '270'}
{'date': '2017-04-01', 'value': '274'}
{'date': '2017-07-01', 'value': '283'}
{'date': '2017-10-01', 'value': '277'}
{'date': '2010-01-01', 'value': '36.950146627565985'}
{'date': '2010-04-01', 'value': '37.391304347826086'}
{'date': '2010-07-01', 'value': '36.53566229985444'}
{'date': '2010-10-01', 'value': '36.32416787264833'}
{'date': '2011-01-01', 'value': '36.075036075036074'}
{'date': '2011-04-01', 'value': '35.67251461988304'}
{'date': '2011-07-01', 'value': '34.801762114537446'}
{'date': '2011-10-01', 'value': '35.08771929824561'}
{'date': '2012-01-01', 'value': '35.095447870778266'}
{'date': '2012-04-01', 'value': '34.39767779390421'}
{'date': '2012-07-01', 'value': '34.06432748538012'}
{'date': '2012-10-01', 'value': '34.35225618631732'}
{'date': '2013-01-01', 'value': '34.25253991291727'}
{'date': '2013-04-01', 'value': '33.9155749636099'}
{'date': '2013-07-01', 'value': '34.55056179775281'}
{'date': '2013-10-01', 'value': '33.848314606741575'}
{'date': '2014-01-01', 'value': '33.147632311977716'}
{'date': '2014-04-01', 'value': '33.100558659217874'}
{'date': '2014-07-01', 'value': '32.53856942496493'}
{'date': '2014-10-01', 'value': '32.7247191011236'}
{'date': '2015-01-01', 'value': '30.942334739803094'}
{'date': '2015-04-01', 'value': '31.875881523272216'}
{'date': '2015-07-01', 'value': '32.63009845288326'}
{'date': '2015-10-01', 'value': '32.58110014104372'}
{'date': '2016-01-01', 'value': '32.212885154061624'}
{'date': '2016-04-01', 'value': '33.00835654596101'}
{'date': '2016-07-01', 'value': '31.98324022346369'}
{'date': '2016-10-01', 'value': '28.92561983471074'}
{'date': '2017-01-01', 'value': '27.434842249657066'}
{'date': '2017-04-01', 'value': '28.70748299319728'}
{'date': '2017-07-01', 'value': '28.6493860845839'}
{'date': '2017-10-01', 'value': '29.807692307692307'}
{'date': '2010-01-01', 'value': '283.0'}
{'date': '2011-01-01', 'value': '257.0'}
{'date': '2012-01-01', 'value': '193.0'}
{'date': '2013-01-01', 'value': '136.0'}
{'date': '2014-01-01', 'value': '156.0'}
{'date': '2015-01-01', 'value': '167.0'}
{'date': '2016-01-01', 'value': '187.0'}
{'date': '2017-01-01', 'value': '186.0'}
{'date': '2010-01-01', 'value': '303186'}
{'date': '2011-01-01', 'value': '307979'}
{'date': '2012-01-01', 'value': '321344'}
{'date': '2013-01-01', 'value': '325289'}
{'date': '2014-01-01', 'value': '330393'}
{'date': '2015-01-01', 'value': '343591'}
{'date': '2016-01-01', 'value': '350450'}
{'date': '2017-01-01', 'value': '361170'}
{'date': '2010-01-01', 'value': '57938'}
{'date': '2011-01-01', 'value': '57586'}
{'date': '2012-01-01', 'value': '57680'}
{'date': '2013-01-01', 'value': '61049'}
{'date': '2014-01-01', 'value': '62812'}
{'date': '2015-01-01', 'value': '69771'}
{'date': '2016-01-01', 'value': '67646'}
{'date': '2017-01-01', 'value': '67722'}
{'date': '2010-01-01', 'value': '60884'}
{'date': '2011-01-01', 'value': '62546'}
{'date': '2012-01-01', 'value': '66582'}
{'date': '2013-01-01', 'value': '65927'}
{'date': '2014-01-01', 'value': '65961'}
{'date': '2015-01-01', 'value': '66956'}
{'date': '2016-01-01', 'value': '68447'}
{'date': '2017-01-01', 'value': '70019'}
{'date': '2010-01-01', 'value': '184364'}
{'date': '2011-01-01', 'value': '187847'}
{'date': '2012-01-01', 'value': '197082'}
{'date': '2013-01-01', 'value': '198313'}
{'date': '2014-01-01', 'value': '201620'}
{'date': '2015-01-01', 'value': '206863'}
{'date': '2016-01-01', 'value': '214357'}
{'date': '2017-01-01', 'value': '223429'}
{'date': '2010-01-01', 'value': '76.6'}
{'date': '2011-01-01', 'value': '77'}
{'date': '2012-01-01', 'value': '78.8'}
{'date': '2013-01-01', 'value': '78.5'}
{'date': '2014-01-01', 'value': '79.1'}
{'date': '2015-01-01', 'value': '79.3'}
{'date': '2016-01-01', 'value': '81.7'}
{'date': '2017-01-01', 'value': '82.8'}
{'date': '2010-01-01', 'value': '12.6'}
{'date': '2011-01-01', 'value': '11.4'}
{'date': '2012-01-01', 'value': '10.6'}
{'date': '2013-01-01', 'value': '10.3'}
{'date': '2014-01-01', 'value': '10.0'}
{'date': '2015-01-01', 'value': '10.8'}
{'date': '2016-01-01', 'value': '12.2'}
{'date': '2017-01-01', 'value': '12.8'}
{'date': '2010-01-01', 'value': '84.31432596312855'}
{'date': '2011-01-01', 'value': '81.37369751525988'}
{'date': '2012-01-01', 'value': '80.34810517220097'}
{'date': '2013-01-01', 'value': '79.9691262735412'}
{'date': '2014-01-01', 'value': '77.72687879163055'}
{'date': '2015-01-01', 'value': '77.33607067313675'}
{'date': '2016-01-01', 'value': '78.00925925925925'}
{'date': '2017-01-01', 'value': '77.28866624921729'}
{'date': '2010-01-01', 'value': '12.3'}
{'date': '2011-01-01', 'value': '11.4'}
{'date': '2012-01-01', 'value': '9.8'}
{'date': '2013-01-01', 'value': '9.8'}
{'date': '2014-01-01', 'value': '8.8'}
{'date': '2015-01-01', 'value': '7.7'}
{'date': '2016-01-01', 'value': '7.1'}
{'date': '2017-01-01', 'value': '5.4'}
{'date': '2010-01-01', 'value': '1031'}
{'date': '2010-02-01', 'value': '1007'}
{'date': '2010-03-01', 'value': '958'}
{'date': '2010-04-01', 'value': '844'}
{'date': '2010-05-01', 'value': '846'}
{'date': '2010-06-01', 'value': '838'}
{'date': '2010-07-01', 'value': '969'}
{'date': '2010-08-01', 'value': '915'}
{'date': '2010-09-01', 'value': '795'}
{'date': '2010-10-01', 'value': '758'}
{'date': '2010-11-01', 'value': '819'}
{'date': '2010-12-01', 'value': '846'}
{'date': '2011-01-01', 'value': '955'}
{'date': '2011-02-01', 'value': '1040'}
{'date': '2011-03-01', 'value': '1037'}
{'date': '2011-04-01', 'value': '780'}
{'date': '2011-05-01', 'value': '756'}
{'date': '2011-06-01', 'value': '840'}
{'date': '2011-07-01', 'value': '796'}
{'date': '2011-08-01', 'value': '756'}
{'date': '2011-09-01', 'value': '753'}
{'date': '2011-10-01', 'value': '688'}
{'date': '2011-11-01', 'value': '642'}
{'date': '2011-12-01', 'value': '710'}
{'date': '2012-01-01', 'value': '744'}
{'date': '2012-02-01', 'value': '727'}
{'date': '2012-03-01', 'value': '688'}
{'date': '2012-04-01', 'value': '631'}
{'date': '2012-05-01', 'value': '664'}
{'date': '2012-06-01', 'value': '728'}
{'date': '2012-07-01', 'value': '729'}
{'date': '2012-08-01', 'value': '680'}
{'date': '2012-09-01', 'value': '639'}
{'date': '2012-10-01', 'value': '632'}
{'date': '2012-11-01', 'value': '631'}
{'date': '2012-12-01', 'value': '701'}
{'date': '2013-01-01', 'value': '788'}
{'date': '2013-02-01', 'value': '713'}
{'date': '2013-03-01', 'value': '703'}
{'date': '2013-04-01', 'value': '655'}
{'date': '2013-05-01', 'value': '664'}
{'date': '2013-06-01', 'value': '723'}
{'date': '2013-07-01', 'value': '696'}
{'date': '2013-08-01', 'value': '647'}
{'date': '2013-09-01', 'value': '656'}
{'date': '2013-10-01', 'value': '636'}
{'date': '2013-11-01', 'value': '605'}
{'date': '2013-12-01', 'value': '604'}
{'date': '2014-01-01', 'value': '645'}
{'date': '2014-02-01', 'value': '619'}
{'date': '2014-03-01', 'value': '628'}
{'date': '2014-04-01', 'value': '545'}
{'date': '2014-05-01', 'value': '546'}
{'date': '2014-06-01', 'value': '605'}
{'date': '2014-07-01', 'value': '618'}
{'date': '2014-08-01', 'value': '579'}
{'date': '2014-09-01', 'value': '568'}
{'date': '2014-10-01', 'value': '555'}
{'date': '2014-11-01', 'value': '558'}
{'date': '2014-12-01', 'value': '579'}
{'date': '2015-01-01', 'value': '638'}
{'date': '2015-02-01', 'value': '573'}
{'date': '2015-03-01', 'value': '563'}
{'date': '2015-04-01', 'value': '496'}
{'date': '2015-05-01', 'value': '519'}
{'date': '2015-06-01', 'value': '563'}
{'date': '2015-07-01', 'value': '538'}
{'date': '2015-08-01', 'value': '502'}
{'date': '2015-09-01', 'value': '480'}
{'date': '2015-10-01', 'value': '443'}
{'date': '2015-11-01', 'value': '453'}
{'date': '2015-12-01', 'value': '453'}
{'date': '2016-01-01', 'value': '578'}
{'date': '2016-02-01', 'value': '511'}
{'date': '2016-03-01', 'value': '493'}
{'date': '2016-04-01', 'value': '442'}
{'date': '2016-05-01', 'value': '423'}
{'date': '2016-06-01', 'value': '518'}
{'date': '2016-07-01', 'value': '514'}
{'date': '2016-08-01', 'value': '497'}
{'date': '2016-09-01', 'value': '491'}
{'date': '2016-10-01', 'value': '440'}
{'date': '2016-11-01', 'value': '404'}
{'date': '2016-12-01', 'value': '419'}
{'date': '2017-01-01', 'value': '497'}
{'date': '2017-02-01', 'value': '419'}
{'date': '2017-03-01', 'value': '381'}
{'date': '2017-04-01', 'value': '313'}
{'date': '2017-05-01', 'value': '311'}
{'date': '2017-06-01', 'value': '388'}
{'date': '2017-07-01', 'value': '373'}
{'date': '2017-08-01', 'value': '342'}
{'date': '2017-09-01', 'value': '320'}
{'date': '2017-10-01', 'value': '334'}
{'date': '2017-11-01', 'value': '337'}
{'date': '2017-12-01', 'value': '359'}

{'date': '2010-01-01', 'value': '886'}
{'date': '2011-01-01', 'value': '813'}
{'date': '2012-01-01', 'value': '683'}
{'date': '2013-01-01', 'value': '674'}
{'date': '2014-01-01', 'value': '587'}
{'date': '2015-01-01', 'value': '518'}
{'date': '2016-01-01', 'value': '478'}
{'date': '2017-01-01', 'value': '365'}
{'date': '2010-01-01', 'value': '6071'}
{'date': '2010-02-01', 'value': '6106'}
{'date': '2010-03-01', 'value': '6275'}
{'date': '2010-04-01', 'value': '6433'}
{'date': '2010-05-01', 'value': '6422'}
{'date': '2010-06-01', 'value': '6285'}
{'date': '2010-07-01', 'value': '6147'}
{'date': '2010-08-01', 'value': '6403'}
{'date': '2010-09-01', 'value': '6528'}
{'date': '2010-10-01', 'value': '6387'}
{'date': '2010-11-01', 'value': '6358'}
{'date': '2010-12-01', 'value': '6358'}
{'date': '2011-01-01', 'value': '6253'}
{'date': '2011-02-01', 'value': '6182'}
{'date': '2011-03-01', 'value': '6210'}
{'date': '2011-04-01', 'value': '6379'}
{'date': '2011-05-01', 'value': '6444'}
{'date': '2011-06-01', 'value': '6552'}
{'date': '2011-07-01', 'value': '5985'}
{'date': '2011-08-01', 'value': '6411'}
{'date': '2011-09-01', 'value': '6391'}
{'date': '2011-10-01', 'value': '6327'}
{'date': '2011-11-01', 'value': '6356'}
{'date': '2011-12-01', 'value': '6342'}
{'date': '2012-01-01', 'value': '6202'}
{'date': '2012-02-01', 'value': '6272'}
{'date': '2012-03-01', 'value': '6291'}
{'date': '2012-04-01', 'value': '6391'}
{'date': '2012-05-01', 'value': '6407'}
{'date': '2012-06-01', 'value': '6499'}
{'date': '2012-07-01', 'value': '5966'}
{'date': '2012-08-01', 'value': '6124'}
{'date': '2012-09-01', 'value': '6301'}
{'date': '2012-10-01', 'value': '6324'}
{'date': '2012-11-01', 'value': '6289'}
{'date': '2012-12-01', 'value': '6288'}
{'date': '2013-01-01', 'value': '6229'}
{'date': '2013-02-01', 'value': '6228'}
{'date': '2013-03-01', 'value': '6310'}
{'date': '2013-04-01', 'value': '6296'}
{'date': '2013-05-01', 'value': '6372'}
{'date': '2013-06-01', 'value': '6349'}
{'date': '2013-07-01', 'value': '5983'}
{'date': '2013-08-01', 'value': '5922'}
{'date': '2013-09-01', 'value': '6232'}
{'date': '2013-10-01', 'value': '6191'}
{'date': '2013-11-01', 'value': '6204'}
{'date': '2013-12-01', 'value': '6165'}
{'date': '2014-01-01', 'value': '6094'}
{'date': '2014-02-01', 'value': '6097'}
{'date': '2014-03-01', 'value': '6184'}
{'date': '2014-04-01', 'value': '6158'}
{'date': '2014-05-01', 'value': '6186'}
{'date': '2014-06-01', 'value': '6106'}
{'date': '2014-07-01', 'value': '5759'}
{'date': '2014-08-01', 'value': '6069'}
{'date': '2014-09-01', 'value': '6160'}
{'date': '2014-10-01', 'value': '6176'}
{'date': '2014-11-01', 'value': '6155'}
{'date': '2014-12-01', 'value': '6131'}
{'date': '2015-01-01', 'value': '6179'}
{'date': '2015-02-01', 'value': '6247'}
{'date': '2015-03-01', 'value': '6303'}
{'date': '2015-04-01', 'value': '6332'}
{'date': '2015-05-01', 'value': '6382'}
{'date': '2015-06-01', 'value': '6506'}
{'date': '2015-07-01', 'value': '5987'}
{'date': '2015-08-01', 'value': '6055'}
{'date': '2015-09-01', 'value': '6188'}
{'date': '2015-10-01', 'value': '6250'}
{'date': '2015-11-01', 'value': '6165'}
{'date': '2015-12-01', 'value': '6199'}
{'date': '2016-01-01', 'value': '6217'}
{'date': '2016-02-01', 'value': '6299'}
{'date': '2016-03-01', 'value': '6379'}
{'date': '2016-04-01', 'value': '6301'}
{'date': '2016-05-01', 'value': '6359'}
{'date': '2016-06-01', 'value': '6255'}
{'date': '2016-07-01', 'value': '6142'}
{'date': '2016-08-01', 'value': '6138'}
{'date': '2016-09-01', 'value': '6241'}
{'date': '2016-10-01', 'value': '6265'}
{'date': '2016-11-01', 'value': '6203'}
{'date': '2016-12-01', 'value': '6187'}
{'date': '2017-01-01', 'value': '6229'}
{'date': '2017-02-01', 'value': '6299'}
{'date': '2017-03-01', 'value': '6404'}
{'date': '2017-04-01', 'value': '6424'}
{'date': '2017-05-01', 'value': '6415'}
{'date': '2017-06-01', 'value': '6274'}
{'date': '2017-07-01', 'value': '6280'}
{'date': '2017-08-01', 'value': '6397'}
{'date': '2017-09-01', 'value': '6440'}
{'date': '2017-10-01', 'value': '6347'}
{'date': '2017-11-01', 'value': '6299'}
{'date': '2017-12-01', 'value': '6374'}
{'date': '2010-01-01', 'value': '6314'}
{'date': '2011-01-01', 'value': '6319'}
{'date': '2012-01-01', 'value': '6280'}
{'date': '2013-01-01', 'value': '6207'}
{'date': '2014-01-01', 'value': '6106'}
{'date': '2015-01-01', 'value': '6233'}
{'date': '2016-01-01', 'value': '6249'}
{'date': '2017-01-01', 'value': '6349'}
{'date': '2010-01-01', 'value': '7200'}
{'date': '2011-01-01', 'value': '7132'}
{'date': '2012-01-01', 'value': '6963'}
{'date': '2013-01-01', 'value': '6881'}
{'date': '2014-01-01', 'value': '6693'}
{'date': '2015-01-01', 'value': '6751'}
{'date': '2016-01-01', 'value': '6727'}
{'date': '2017-01-01', 'value': '6714'}
{'date': '2010-01-01', 'value': '29774'}
{'date': '2011-01-01', 'value': '29365'}
{'date': '2012-01-01', 'value': '30675'}
{'date': '2013-01-01', 'value': '32731'}
{'date': '2014-01-01', 'value': '31024'}
{'date': '2015-01-01', 'value': '32918'}
{'date': '2016-01-01', 'value': '32147'}
{'date': '2017-01-01', 'value': '32360'}
{'date': '2010-01-01', 'value': '34918'}
{'date': '2011-01-01', 'value': '35689'}
{'date': '2012-01-01', 'value': '36445'}
{'date': '2013-01-01', 'value': '38387'}
{'date': '2014-01-01', 'value': '37740'}
{'date': '2015-01-01', 'value': '39484'}
{'date': '2016-01-01', 'value': '39299'}
{'date': '2017-01-01', 'value': '39708'}
{'date': '2010-01-01', 'value': '32346'}
{'date': '2011-01-01', 'value': '32527'}
{'date': '2012-01-01', 'value': '33560'}
{'date': '2013-01-01', 'value': '35559'}
{'date': '2014-01-01', 'value': '34382'}
{'date': '2015-01-01', 'value': '36201'}
{'date': '2016-01-01', 'value': '35723'}
{'date': '2017-01-01', 'value': '36034'}
{'date': '2010-01-01', 'value': '288.0'}
{'date': '2011-01-01', 'value': '-161.0'}
{'date': '2012-01-01', 'value': '-129.0'}
{'date': '2013-01-01', 'value': '-207.0'}
{'date': '2014-01-01', 'value': '-198.0'}
{'date': '2015-01-01', 'value': '-198.0'}
{'date': '2016-01-01', 'value': '-67.0'}
{'date': '2017-01-01', 'value': '0.0'}
{'date': '2010-01-01', 'value': '27921'}
{'date': '2011-01-01', 'value': '28987'}
{'date': '2012-01-01', 'value': '29708'}
{'date': '2013-01-01', 'value': '29763'}
{'date': '2014-01-01', 'value': '29948'}
{'date': '2015-01-01', 'value': '30883'}
{'date': '2016-01-01', 'value': '31567'}
{'date': '2017-01-01', 'value': '32715'}
{'date': '2010-01-01', 'value': '760'}
{'date': '2011-01-01', 'value': '762'}
{'date': '2012-01-01', 'value': '804'}
{'date': '2013-01-01', 'value': '767'}
{'date': '2014-01-01', 'value': '725'}
{'date': '2015-01-01', 'value': '685'}
{'date': '2016-01-01', 'value': '640'}
{'date': '2017-01-01', 'value': '643'}
{'date': '2010-01-01', 'value': '3242'}
{'date': '2011-01-01', 'value': '3425'}
{'date': '2012-01-01', 'value': '3715'}
{'date': '2013-01-01', 'value': '3420'}
{'date': '2014-01-01', 'value': '3420'}
{'date': '2015-01-01', 'value': '3265'}
{'date': '2016-01-01', 'value': '2831'}
{'date': '2017-01-01', 'value': '2970'}
{'date': '2010-01-01', 'value': '577'}
{'date': '2011-01-01', 'value': '572'}
{'date': '2012-01-01', 'value': '631'}
{'date': '2013-01-01', 'value': '572'}
{'date': '2014-01-01', 'value': '552'}
{'date': '2015-01-01', 'value': '516'}
{'date': '2016-01-01', 'value': '471'}
{'date': '2017-01-01', 'value': '466'}
{'date': '2010-01-01', 'value': '2525'}
{'date': '2011-01-01', 'value': '2728'}
{'date': '2012-01-01', 'value': '3091'}
{'date': '2013-01-01', 'value': '2723'}
{'date': '2014-01-01', 'value': '2776'}
{'date': '2015-01-01', 'value': '2642'}
{'date': '2016-01-01', 'value': '2240'}
{'date': '2017-01-01', 'value': '2377'}
{'date': '2010-01-01', 'value': '842'}
{'date': '2011-01-01', 'value': '864'}
{'date': '2012-01-01', 'value': '897'}
{'date': '2013-01-01', 'value': '882'}
{'date': '2014-01-01', 'value': '789'}
{'date': '2015-01-01', 'value': '794'}
{'date': '2016-01-01', 'value': '701'}
{'date': '2017-01-01', 'value': '670'}
{'date': '2010-01-01', 'value': '943'}
{'date': '2011-01-01', 'value': '952'}
{'date': '2012-01-01', 'value': '977'}
{'date': '2013-01-01', 'value': '962'}
{'date': '2014-01-01', 'value': '898'}
{'date': '2015-01-01', 'value': '854'}
{'date': '2016-01-01', 'value': '809'}
{'date': '2017-01-01', 'value': '820'}

{'date': '2010-01-01', 'value': '3959'}
{'date': '2011-01-01', 'value': '4122'}
{'date': '2012-01-01', 'value': '4339'}
{'date': '2013-01-01', 'value': '4117'}
{'date': '2014-01-01', 'value': '4064'}
{'date': '2015-01-01', 'value': '3888'}
{'date': '2016-01-01', 'value': '3422'}
{'date': '2017-01-01', 'value': '3563'}
{'date': '2010-01-01', 'value': '1384'}
{'date': '2011-01-01', 'value': '1380'}
{'date': '2012-01-01', 'value': '1377'}
{'date': '2013-01-01', 'value': '1376'}
{'date': '2014-01-01', 'value': '1271'}
{'date': '2015-01-01', 'value': '1234'}
{'date': '2016-01-01', 'value': '1163'}
{'date': '2017-01-01', 'value': '1142'}
{'date': '2010-01-01', 'value': '1113'}
{'date': '2011-01-01', 'value': '1122'}
{'date': '2012-01-01', 'value': '1137'}
{'date': '2013-01-01', 'value': '1129'}
{'date': '2014-01-01', 'value': '1030'}
{'date': '2015-01-01', 'value': '1014'}
{'date': '2016-01-01', 'value': '932'}
{'date': '2017-01-01', 'value': '906'}
{'date': '2010-01-01', 'value': '461002'}
{'date': '2011-01-01', 'value': '477945'}
{'date': '2012-01-01', 'value': '487628'}
{'date': '2013-01-01', 'value': '486928'}
{'date': '2014-01-01', 'value': '484342'}
{'date': '2015-01-01', 'value': '499814'}
{'date': '2016-01-01', 'value': '506908'}
{'date': '2017-01-01', 'value': '522095'}
{'date': '2010-01-01', 'value': '31.1'}
{'date': '2011-01-01', 'value': '31.9'}
{'date': '2012-01-01', 'value': '34.4'}
{'date': '2013-01-01', 'value': '33.0'}
{'date': '2014-01-01', 'value': '31.5'}
{'date': '2015-01-01', 'value': '29.6'}
{'date': '2016-01-01', 'value': '28'}
{'date': '2017-01-01', 'value': '28.7'}
{'date': '2010-01-01', 'value': '19.9'}
{'date': '2011-01-01', 'value': '21.1'}
{'date': '2012-01-01', 'value': '23.0'}
{'date': '2013-01-01', 'value': '21.3'}
{'date': '2014-01-01', 'value': '21.4'}
{'date': '2015-01-01', 'value': '20.5'}
{'date': '2016-01-01', 'value': '17.9'}
{'date': '2017-01-01', 'value': '18.8'}
{'date': '2010-01-01', 'value': '23.6'}
{'date': '2011-01-01', 'value': '23.9'}
{'date': '2012-01-01', 'value': '27.0'}
{'date': '2013-01-01', 'value': '24.6'}
{'date': '2014-01-01', 'value': '24.0'}
{'date': '2015-01-01', 'value': '22.3'}
{'date': '2016-01-01', 'value': '20.6'}
{'date': '2017-01-01', 'value': '20.8'}
{'date': '2010-01-01', 'value': '15.5'}
{'date': '2011-01-01', 'value': '16.8'}
{'date': '2012-01-01', 'value': '19.1'}
{'date': '2013-01-01', 'value': '17.0'}
{'date': '2014-01-01', 'value': '17.4'}
{'date': '2015-01-01', 'value': '16.6'}
{'date': '2016-01-01', 'value': '14.2'}
{'date': '2017-01-01', 'value': '15'}
{'date': '2010-01-01', 'value': '25.7'}
{'date': '2011-01-01', 'value': '26.6'}
{'date': '2012-01-01', 'value': '28.2'}
{'date': '2013-01-01', 'value': '27.8'}
{'date': '2014-01-01', 'value': '25.3'}
{'date': '2015-01-01', 'value': '25.2'}
{'date': '2016-01-01', 'value': '22.6'}
{'date': '2017-01-01', 'value': '22'}
{'date': '2010-01-01', 'value': '38.6'}
{'date': '2011-01-01', 'value': '39.9'}
{'date': '2012-01-01', 'value': '41.8'}
{'date': '2013-01-01', 'value': '41.4'}
{'date': '2014-01-01', 'value': '39.0'}
{'date': '2015-01-01', 'value': '36.9'}
{'date': '2016-01-01', 'value': '35.4'}
{'date': '2017-01-01', 'value': '36.6'}
{'date': '2010-01-01', 'value': '24.3'}
{'date': '2011-01-01', 'value': '25.4'}
{'date': '2012-01-01', 'value': '26.9'}
{'date': '2013-01-01', 'value': '25.6'}
{'date': '2014-01-01', 'value': '25.4'}
{'date': '2015-01-01', 'value': '24.4'}
{'date': '2016-01-01', 'value': '21.6'}
{'date': '2017-01-01', 'value': '22.6'}
{'date': '2010-01-01', 'value': '42.1'}
{'date': '2011-01-01', 'value': '42.4'}
{'date': '2012-01-01', 'value': '43.2'}
{'date': '2013-01-01', 'value': '43.4'}
{'date': '2014-01-01', 'value': '40.7'}
{'date': '2015-01-01', 'value': '39.2'}
{'date': '2016-01-01', 'value': '37.6'}
{'date': '2017-01-01', 'value': '37.4'}
{'date': '2010-01-01', 'value': '33.9'}
{'date': '2011-01-01', 'value': '34.5'}
{'date': '2012-01-01', 'value': '35.7'}
{'date': '2013-01-01', 'value': '35.6'}
{'date': '2014-01-01', 'value': '33.0'}
{'date': '2015-01-01', 'value': '32.2'}
{'date': '2016-01-01', 'value': '30.1'}
{'date': '2017-01-01', 'value': '29.7'}
{'date': '2010-01-01', 'value': '3284'}
{'date': '2011-01-01', 'value': '3250'}
{'date': '2012-01-01', 'value': '3187'}
{'date': '2013-01-01', 'value': '3172'}
{'date': '2014-01-01', 'value': '3121'}
{'date': '2015-01-01', 'value': '3149'}
{'date': '2016-01-01', 'value': '3094'}
{'date': '2017-01-01', 'value': '3053'}
{'date': '2010-01-01', 'value': '2444'}
{'date': '2011-01-01', 'value': '2385'}
{'date': '2012-01-01', 'value': '2334'}
{'date': '2013-01-01', 'value': '2324'}
{'date': '2014-01-01', 'value': '2303'}
{'date': '2015-01-01', 'value': '2316'}
{'date': '2016-01-01', 'value': '2289'}
{'date': '2017-01-01', 'value': '2237'}
{'date': '2010-01-01', 'value': '16300'}
{'date': '2011-01-01', 'value': '16242'}
{'date': '2012-01-01', 'value': '16166'}
{'date': '2013-01-01', 'value': '16094'}
{'date': '2014-01-01', 'value': '15949'}
{'date': '2015-01-01', 'value': '15936'}
{'date': '2016-01-01', 'value': '15816'}
{'date': '2017-01-01', 'value': '15795'}
{'date': '2010-01-01', 'value': '49.57377112628183'}
{'date': '2011-01-01', 'value': '45.09268957568162'}
{'date': '2012-01-01', 'value': '44.70319527579111'}
{'date': '2013-01-01', 'value': '24.18745917933966'}
{'date': '2014-01-01', 'value': '25.693727949514532'}
{'date': '2015-01-01', 'value': '26.576854046958925'}
{'date': '2016-01-01', 'value': '27.081786330107793'}
{'date': '2017-01-01', 'value': '23.598862724249724'}
{'date': '2010-01-01', 'value': '317922'}
{'date': '2011-01-01', 'value': '316348'}
{'date': '2012-01-01', 'value': '321344'}
{'date': '2013-01-01', 'value': '316813'}
{'date': '2014-01-01', 'value': '313649'}
{'date': '2015-01-01', 'value': '317344'}
{'date': '2016-01-01', 'value': '317442'}
{'date': '2017-01-01', 'value': '320424'}
{'date': '2010-01-01', 'value': '62270'}
{'date': '2011-01-01', 'value': '59386'}
{'date': '2012-01-01', 'value': '57680'}
{'date': '2013-01-01', 'value': '59334'}
{'date': '2014-01-01', 'value': '58992'}
{'date': '2015-01-01', 'value': '64099'}
{'date': '2016-01-01', 'value': '61535'}
{'date': '2017-01-01', 'value': '59800'}
{'date': '2010-01-01', 'value': '63201'}
{'date': '2011-01-01', 'value': '63894'}
{'date': '2012-01-01', 'value': '66582'}
{'date': '2013-01-01', 'value': '63470'}
{'date': '2014-01-01', 'value': '61623'}
{'date': '2015-01-01', 'value': '60619'}
{'date': '2016-01-01', 'value': '61346'}
{'date': '2017-01-01', 'value': '61684'}
{'date': '2010-01-01', 'value': '192485'}
{'date': '2011-01-01', 'value': '193079'}
{'date': '2012-01-01', 'value': '197082'}
{'date': '2013-01-01', 'value': '194019'}
{'date': '2014-01-01', 'value': '193066'}
{'date': '2015-01-01', 'value': '192629'}
{'date': '2016-01-01', 'value': '194569'}
{'date': '2017-01-01', 'value': '198960'}
{'date': '2010-01-01', 'value': '34.457142857142856'}
{'date': '2011-01-01', 'value': '31.61592505854801'}
{'date': '2012-01-01', 'value': '33.549528301886795'}
{'date': '2013-01-01', 'value': '35.6651376146789'}
{'date': '2014-01-01', 'value': '36.7359413202934'}
{'date': '2015-01-01', 'value': '33.26502732240437'}
{'date': '2016-01-01', 'value': '30.444282592862344'}
{'date': '2017-01-01', 'value': '37.77777777777778'}
{'date': '2010-01-01', 'value': '15.7'}
{'date': '2011-01-01', 'value': '14.4'}
{'date': '2012-01-01', 'value': '13.6'}
{'date': '2013-01-01', 'value': '13.599999999999998'}
{'date': '2014-01-01', 'value': '14.100000000000001'}
{'date': '2015-01-01', 'value': '14.5'}
{'date': '2016-01-01', 'value': '16.7'}
{'date': '2017-01-01', 'value': '17.8'}
{'date': '2012-01-01', 'value': '20.4'}
{'date': '2013-01-01', 'value': '22.1'}
{'date': '2014-01-01', 'value': '21.8'}
{'date': '2015-01-01', 'value': '22.8'}
{'date': '2016-01-01', 'value': '22.6'}
{'date': '2017-01-01', 'value': '22.3'}
{'date': '2010-01-01', 'value': '7102'}
{'date': '2010-02-01', 'value': '7113'}
{'date': '2010-03-01', 'value': '7233'}
{'date': '2010-04-01', 'value': '7277'}
{'date': '2010-05-01', 'value': '7268'}
{'date': '2010-06-01', 'value': '7123'}
{'date': '2010-07-01', 'value': '7116'}
{'date': '2010-08-01', 'value': '7318'}
{'date': '2010-09-01', 'value': '7323'}
{'date': '2010-10-01', 'value': '7145'}
{'date': '2010-11-01', 'value': '7177'}
{'date': '2010-12-01', 'value': '7204'}
{'date': '2011-01-01', 'value': '7208'}
{'date': '2011-02-01', 'value': '7222'}
{'date': '2011-03-01', 'value': '7247'}
{'date': '2011-04-01', 'value': '7159'}
{'date': '2011-05-01', 'value': '7200'}
{'date': '2011-06-01', 'value': '7392'}
{'date': '2011-07-01', 'value': '6781'}
{'date': '2011-08-01', 'value': '7167'}
{'date': '2011-09-01', 'value': '7144'}
{'date': '2011-10-01', 'value': '7015'}
{'date': '2011-11-01', 'value': '6998'}
{'date': '2011-12-01', 'value': '7052'}
{'date': '2012-01-01', 'value': '6946'}
{'date': '2012-02-01', 'value': '6999'}
{'date': '2012-03-01', 'value': '6979'}
{'date': '2012-04-01', 'value': '7022'}
{'date': '2012-05-01', 'value': '7071'}
{'date': '2012-06-01', 'value': '7227'}
{'date': '2012-07-01', 'value': '6695'}
{'date': '2012-08-01', 'value': '6804'}
{'date': '2012-09-01', 'value': '6940'}
{'date': '2012-10-01', 'value': '6956'}
{'date': '2012-11-01', 'value': '6920'}
{'date': '2012-12-01', 'value': '6989'}
{'date': '2013-01-01', 'value': '7017'}
{'date': '2013-02-01', 'value': '6941'}
{'date': '2013-03-01', 'value': '7013'}
{'date': '2013-04-01', 'value': '6951'}
{'date': '2013-05-01', 'value': '7036'}
{'date': '2013-06-01', 'value': '7072'}
{'date': '2013-07-01', 'value': '6679'}
{'date': '2013-08-01', 'value': '6569'}
{'date': '2013-09-01', 'value': '6888'}
{'date': '2013-10-01', 'value': '6827'}
{'date': '2013-11-01', 'value': '6809'}
{'date': '2013-12-01', 'value': '6769'}
{'date': '2014-01-01', 'value': '6739'}
{'date': '2014-02-01', 'value': '6716'}
{'date': '2014-03-01', 'value': '6812'}
{'date': '2014-04-01', 'value': '6703'}
{'date': '2014-05-01', 'value': '6732'}
{'date': '2014-06-01', 'value': '6711'}
{'date': '2014-07-01', 'value': '6377'}
{'date': '2014-08-01', 'value': '6648'}
{'date': '2014-09-01', 'value': '6728'}
{'date': '2014-10-01', 'value': '6731'}
{'date': '2014-11-01', 'value': '6713'}
{'date': '2014-12-01', 'value': '6710'}
{'date': '2015-01-01', 'value': '6817'}
{'date': '2015-02-01', 'value': '6820'}
{'date': '2015-03-01', 'value': '6866'}
{'date': '2015-04-01', 'value': '6828'}
{'date': '2015-05-01', 'value': '6901'}
{'date': '2015-06-01', 'value': '7069'}
{'date': '2015-07-01', 'value': '6525'}
{'date': '2015-08-01', 'value': '6557'}
{'date': '2015-09-01', 'value': '6668'}
{'date': '2015-10-01', 'value': '6693'}
{'date': '2015-11-01', 'value': '6618'}
{'date': '2015-12-01', 'value': '6652'}
{'date': '2016-01-01', 'value': '6795'}
{'date': '2016-02-01', 'value': '6810'}
{'date': '2016-03-01', 'value': '6872'}
{'date': '2016-04-01', 'value': '6743'}
{'date': '2016-05-01', 'value': '6782'}
{'date': '2016-06-01', 'value': '6773'}
{'date': '2016-07-01', 'value': '6656'}
{'date': '2016-08-01', 'value': '6635'}
{'date': '2016-09-01', 'value': '6732'}
{'date': '2016-10-01', 'value': '6705'}
{'date': '2016-11-01', 'value': '6607'}
{'date': '2016-12-01', 'value': '6606'}
{'date': '2017-01-01', 'value': '6726'}
{'date': '2017-02-01', 'value': '6718'}
{'date': '2017-03-01', 'value': '6785'}
{'date': '2017-04-01', 'value': '6737'}
{'date': '2017-05-01', 'value': '6726'}
{'date': '2017-06-01', 'value': '6662'}
{'date': '2017-07-01', 'value': '6653'}
{'date': '2017-08-01', 'value': '6739'}
{'date': '2017-09-01', 'value': '6760'}
{'date': '2017-10-01', 'value': '6681'}
{'date': '2017-11-01', 'value': '6636'}
{'date': '2017-12-01', 'value': '6733'}

{'date': '2010-01-01', 'value': '16.511'}
{'date': '2011-01-01', 'value': '16.529'}
{'date': '2012-01-01', 'value': '16.445'}
{'date': '2013-01-01', 'value': '16.36'}
{'date': '2014-01-01', 'value': '16.197'}
{'date': '2015-01-01', 'value': '16.22'}
{'date': '2016-01-01', 'value': '16.082'}
{'date': '2017-01-01', 'value': '15.993'}
{'date': '2010-01-01', 'value': '14.500'}
{'date': '2010-02-01', 'value': '14.200'}
{'date': '2010-03-01', 'value': '13.200'}
{'date': '2010-04-01', 'value': '11.600'}
{'date': '2010-05-01', 'value': '11.600'}
{'date': '2010-06-01', 'value': '11.800'}
{'date': '2010-07-01', 'value': '13.600'}
{'date': '2010-08-01', 'value': '12.500'}
{'date': '2010-09-01', 'value': '10.900'}
{'date': '2010-10-01', 'value': '10.600'}
{'date': '2010-11-01', 'value': '11.400'}
{'date': '2010-12-01', 'value': '11.700'}
{'date': '2011-01-01', 'value': '13.200'}
{'date': '2011-02-01', 'value': '14.4'}
{'date': '2011-03-01', 'value': '14.300'}
{'date': '2011-04-01', 'value': '10.900'}
{'date': '2011-05-01', 'value': '10.500'}
{'date': '2011-06-01', 'value': '11.4'}
{'date': '2011-07-01', 'value': '11.700'}
{'date': '2011-08-01', 'value': '10.500'}
{'date': '2011-09-01', 'value': '10.500'}
{'date': '2011-10-01', 'value': '9.800'}
{'date': '2011-11-01', 'value': '9.200'}
{'date': '2011-12-01', 'value': '10.1'}
{'date': '2012-01-01', 'value': '10.7'}
{'date': '2012-02-01', 'value': '10.400'}
{'date': '2012-03-01', 'value': '9.900'}
{'date': '2012-04-01', 'value': '9.000'}
{'date': '2012-05-01', 'value': '9.400'}
{'date': '2012-06-01', 'value': '10.100'}
{'date': '2012-07-01', 'value': '10.9'}
{'date': '2012-08-01', 'value': '10.000'}
{'date': '2012-09-01', 'value': '9.2'}
{'date': '2012-10-01', 'value': '9.100'}
{'date': '2012-11-01', 'value': '9.100'}
{'date': '2012-12-01', 'value': '10.0'}
{'date': '2013-01-01', 'value': '11.2'}
{'date': '2013-02-01', 'value': '10.300'}
{'date': '2013-03-01', 'value': '10.0'}
{'date': '2013-04-01', 'value': '9.4'}
{'date': '2013-05-01', 'value': '9.4'}
{'date': '2013-06-01', 'value': '10.2'}
{'date': '2013-07-01', 'value': '10.400'}
{'date': '2013-08-01', 'value': '9.8'}
{'date': '2013-09-01', 'value': '9.5'}
{'date': '2013-10-01', 'value': '9.300'}
{'date': '2013-11-01', 'value': '8.9'}
{'date': '2013-12-01', 'value': '8.9'}
{'date': '2014-01-01', 'value': '9.6'}
{'date': '2014-02-01', 'value': '9.2'}
{'date': '2014-03-01', 'value': '9.2'}
{'date': '2014-04-01', 'value': '8.1'}
{'date': '2014-05-01', 'value': '8.1'}
{'date': '2014-06-01', 'value': '9.0'}
{'date': '2014-07-01', 'value': '9.7'}
{'date': '2014-08-01', 'value': '8.7'}
{'date': '2014-09-01', 'value': '8.4'}
{'date': '2014-10-01', 'value': '8.2'}
{'date': '2014-11-01', 'value': '8.3'}
{'date': '2014-12-01', 'value': '8.6'}
{'date': '2015-01-01', 'value': '9.4'}
{'date': '2015-02-01', 'value': '8.4'}
{'date': '2015-03-01', 'value': '8.2'}
{'date': '2015-04-01', 'value': '7.300'}
{'date': '2015-05-01', 'value': '7.5'}
{'date': '2015-06-01', 'value': '8.0'}
{'date': '2015-07-01', 'value': '8.2'}
{'date': '2015-08-01', 'value': '7.7'}
{'date': '2015-09-01', 'value': '7.2'}
{'date': '2015-10-01', 'value': '6.6'}
{'date': '2015-11-01', 'value': '6.8'}
{'date': '2015-12-01', 'value': '6.8'}
{'date': '2016-01-01', 'value': '8.5'}
{'date': '2016-02-01', 'value': '7.5'}
{'date': '2016-03-01', 'value': '7.2'}
{'date': '2016-04-01', 'value': '6.6'}
{'date': '2016-05-01', 'value': '6.2'}
{'date': '2016-06-01', 'value': '7.6'}
{'date': '2016-07-01', 'value': '7.7'}
{'date': '2016-08-01', 'value': '7.5'}
{'date': '2016-09-01', 'value': '7.3'}
{'date': '2016-10-01', 'value': '6.6'}
{'date': '2016-11-01', 'value': '6.1'}
{'date': '2016-12-01', 'value': '6.3'}
{'date': '2017-01-01', 'value': '7.4'}
{'date': '2017-02-01', 'value': '6.2'}
{'date': '2017-03-01', 'value': '5.6'}
{'date': '2017-04-01', 'value': '4.6'}
{'date': '2017-05-01', 'value': '4.6'}
{'date': '2017-06-01', 'value': '5.8'}
{'date': '2017-07-01', 'value': '5.6'}
{'date': '2017-08-01', 'value': '5.1'}
{'date': '2017-09-01', 'value': '4.7'}
{'date': '2017-10-01', 'value': '5.0'}
{'date': '2017-11-01', 'value': '5.1'}
{'date': '2017-12-01', 'value': '5.3'}